BOOTLOADER = rp2040
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes


VIA_ENABLE = yes
VIAL_ENABLE	= yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
VIALRGB_ENABLE = no
RGB_MATRIX_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
MIDI_ENABLE = yes
OLED_ENABLE = no
